### ISSUE TITLE
Issue after install

### ISSUE THREAD

**Issue by YanSte** [mono0926/alfred-git-commit-message-example#1]
I have this error after install
```
pip install --target=. Alfred-Workflow                                                                    ✔  3867  15:13:17
Collecting Alfred-Workflow
  Downloading https://files.pythonhosted.org/packages/dd/2a/bac5da0c7ad4a6d9c310f4c9aeb6d467e4e687fc83681e6509626be37c22/Alfred-Workflow-1.36.tar.gz (90kB)
    100% |████████████████████████████████| 92kB 3.0MB/s
Building wheels for collected packages: Alfred-Workflow
  Running setup.py bdist_wheel for Alfred-Workflow ... done
  Stored in directory: /Users/yannickstephan/Library/Caches/pip/wheels/10/37/a6/a0d928332f9bf8cd4f8420582a76ee056aa042f5afb27aad93
Successfully built Alfred-Workflow
Installing collected packages: Alfred-Workflow
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 347, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 941, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 526, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/wheel.py", line 215, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python2.7/site-packages/pip/_internal/locations.py", line 165, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both"
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
```

**Comment by mono0926** [comment]
You can [download and install the workflow from here](https://github.com/mono0926/alfred-git-commit-message-example/releases) as written on README.
Latest version(0.2.0) is here:
https://github.com/mono0926/alfred-git-commit-message-example/releases/download/0.2.0/gcme.alfredworkflow

`pip install --target=. Alfred-Workflow` is only needed to develop the workflow.

And, I think the problem is not related to the workflow, but related to Python or [alfred-workflow](https://github.com/deanishe/alfred-workflow).

So, unfortunately I cannot help you.

Thanks.
